### ISSUE TITLE
Instructions for Android React Native without Android Studio

### ISSUE THREAD

**Issue by pickhardt** [corymsmith/react-native-fabric#10]
The instructions say: "Set up Fabric / Crashlytics in your app as instructed on Fabric.io"

For an Android app, the instructions start by assuming you use IntelliJ or Android Studio. What if I am not using either of those? I'm not sure if there's a way to do it without those - do you know?

**Comment by corymsmith** [comment]
I'm sure there is but I wouldn't recommend it. if you sort it out let me know but I'd highly recommend converting your project to Android Studio / gradle if you can.

**Comment by pickhardt** [comment]
Maybe mention something about this on the README? For example, at https://fabric.io/kits/android/crashlytics/install it says to add some Crashlytics code to MainActivity.java, however there is no onCreate in my RN MainActivity.java. This repo says instead to add something to addPackages. Do I need to do both? It is a little bit confusing trying to figure out how to use the Crashlytics installation instructions with a RN app (not your fault or anything, but when trying to use this repo they're all part of a larger Crashlytics+RN installation process).

**Comment by pickhardt** [comment]
OK, so I figured it out. Never mind, I think you just need to say to use that link in the install instructions, because otherwise Crashlytics and Fabric push you really hard to use Android Studio or IntelliJ.

**Comment by kcole16** [comment]
How did you work around the lack on "onCreate" in MainActivity.java?

**Comment by corymsmith** [comment]
@kcole16 Add the package to the array returned from getPackages() in MainActivity.java. 

The structure of the MainActivity changed between RN versions and I haven't updated this guide to match yet.

**Comment by davodesign84** [comment]
Hi guys, I am a bit confused I follow the instructions "I think" correctly, but the Android studio plugin still doesn't find my Fabric + Crashlytics instance, but on the android monitor I can see this `I/Fabric: Initializing Crashlytics 2.3.2.56`

Here I add my package on MainActivity

```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.asList(
              new RNMixpanel(),
              new MainReactPackage(),
              new FabricPackage(this)
      );
    }
```

this is my build.gradle:

```
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        // The Fabric Gradle plugin uses an open ended version to react
        // quickly to Android tooling updates
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

apply plugin: "com.android.application"
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

import com.android.build.OutputFile

apply from: "react.gradle"

.....
 
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile project(':RNMixpanel')
    compile project(':react-native-fabric')
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
}
```

what am I doing wrong?

**Comment by alexprice91** [comment]
Im trying to figure this out too. But I am using the `onCreate` method for another library, so I have that figured out.

`MainActivity` inherits from `ReactActivity` which inherits from `android.app.Application;`

So just do this:

```
public class MainActivity extends ReactActivity {

    @Override
    public void onCreate() {
        super.onCreate();

        // Example: single kit
        // TwitterAuthConfig authConfig =  new TwitterAuthConfig("consumerKey", "consumerSecret");
        // Fabric.with(this, new TwitterCore(authConfig));

        // Example: multiple kits
        // Fabric.with(this, new TwitterCore(authConfig), new TweetUi());
    }
}
```

**Comment by skleest** [comment]
@davodesign84 Have you figured it out from there?

**Comment by alexprice91** [comment]
@skleest @davodesign84 this `Mr Brown's` stackoverflow response helped me:

https://stackoverflow.com/questions/33501522/how-do-i-use-crashlytics-for-my-react-native-android-app/34182131#34182131

**Comment by skleest** [comment]
Thank you @alexprice91, just got it working as well!

**Comment by corymsmith** [comment]
I'd gladly accept a PR with some clarification to the Readme :)

**Comment by GeoffreyPlitt** [comment]
Here's a full commit showing all the changes you need to make for React-Native 0.33. It's different than some of the suggestions I saw. Should probably update your docs.

https://github.com/GeoffreyPlitt/react_native_minimal/commit/64ddc04a4a49d695aaf4d7e3adeac2d420564669
