### ISSUE TITLE
libSMXCrashlutics.a is red,can't found it

### ISSUE THREAD

**Issue by 91hong** [corymsmith/react-native-fabric#103]
RN:0.38
rnpm install react-native-fabric@0.3.2

**Comment by corymsmith** [comment]
You should be using `react-native link`, does it not build for you?

**Comment by lakhman** [comment]
I also had this error, I used "rnpm install react-native-fabric" and also "react-native link react-native-fabric".

I had to manually perform the following step:

```
RN 0.29+ - Edit your MainApplication.java (deep in android/app/src/main/java/...) to look like this (note two places to edit):

package com.myapp;

+ import com.smixx.fabric.FabricPackage;

....
public class MainApplication extends Application implements ReactApplication {
  @Override
  protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
+         new FabricPackage(),
          new MainReactPackage()
      );
  }
}
```

After a clean build and install, everythings working as expected, not sure why rnpm failed to link, but this solved the issue.
