### ISSUE TITLE
[iOS] No visible @interface for 'Crashlytics' declares the selector 'recordError:'

### ISSUE THREAD

**Issue by igorlimansky** [corymsmith/react-native-fabric#106]
I'm trying to install Fabric via CocoaPods in my boilerplate, here is my Podfile:
https://github.com/igorlimansky/react-native-redux-boilerplate/blob/master/ios/Podfile

But I'm getting an error:
.../react-native-boilerplate/node_modules/react-native-fabric/ios/SMXCrashlytics/SMXCrashlytics.m:37:35: No visible @interface for 'Crashlytics' declares the selector 'recordError:'

I'm not very experienced with iOS development and Pods, so I have no idea how to fix, any ideas welcome, thanks!

**Comment by corymsmith** [comment]
I've never included this lib via Podfile before so I'm not much help. You shouldn't need to do that even if you're installing Fabric and Crashlytics via CocoaPods.

**Comment by igorlimansky** [comment]
well, I removed all pods from my project and it works now
