### ISSUE TITLE
Will pending calls still be made after component is unmounted

### ISSUE THREAD

**Issue by robcalcroft** [corymsmith/react-native-fabric#111]
I have some Crashlytics calls that are made as the user logs in. After they login they instantly get redirected to another component and other old one is unmounted. If the Crashlytics calls are not completed before the component unmounts are they lost? Or are the `Crashlytics.X()` calls async?

**Comment by corymsmith** [comment]
They are async and it should have already reached the native module by then as long as you make the call before it gets redirected / the new component is pushed.
