### ISSUE TITLE
TypeError: Cannot read property 'crash' of undefined with Jest

### ISSUE THREAD

**Issue by enstulen** [corymsmith/react-native-fabric#113]
I'm getting the error: TypeError: Cannot read property 'crash' of undefined when testing my components with Jest that has Fabric imported.

Every component that fail has this:
```
import Fabric from 'react-native-fabric';
var { Answers } = Fabric;
```
<img width="564" alt="skjermbilde 2017-04-10 kl 22 56 44" src="https://cloud.githubusercontent.com/assets/7783861/24882432/54905dc0-1e41-11e7-86fb-ed9afdfdd9b7.png">

Example test: 
```
const store = configureStore();

describe('InfoModal-screen', () => {

  it('renders correctly', () => {
    const tree = renderer.create(
        <InfoModal store={store} card={{}}/>
    ).toJSON();
    expect(tree).toMatchSnapshot();
  });

});
```

The app works fine and runs on both iOS and Android, but the tests fail. Anyone know why? 
Any help is greatly appreciated :)

**Comment by corymsmith** [comment]
You would have to mock out this lib so that it's it trying to call the actual native modules

**Comment by enstulen** [comment]
Thanks for the reply! I tried using mockery without any luck. I added this in my setup.js file for jest.  
```
mockery.enable();
mockery.warnOnUnregistered(false);
mockery.registerMock('react-native-fabric', {
  Crashlytics: {
    crash: () => {},
  },
});
```
Package.json:
```
  "jest": {
    "preset": "react-native",
    "coverageDirectory": ".coverage/",
    "setupFiles": [
      "<rootDir>/jest/setup.js"
    ]
  }
```

**Comment by enstulen** [comment]
I got it working by using:
```
jest.mock('react-native-fabric', () => {
  return {
    Crashlytics: {
      crash: () => {},
    },
    Answers: {
      logCustom: () => {},
      logContentView: () => {},
    },
  }
})
```

**Comment by corymsmith** [comment]
Awesome, great to hear

**Comment by oded-regev** [comment]
@enstulen can you please specify where exactly should I add this code?

**Comment by enstulen** [comment]
The mock code is In a setup.js file which I placed in "<rootDir>/jest/setup.js" 
This is in my package.json file:

```
  "jest": {
    "preset": "react-native",
    "coverageDirectory": ".coverage/",
    "setupFiles": [
      "<rootDir>/jest/setup.js"
    ]
  }
```
