### ISSUE TITLE
Android - Gradle - Build Tools - Gradle plugin 2.2.x to 2.3.x requires build tools 25.x

### ISSUE THREAD

**Issue by rafaelchiti** [corymsmith/react-native-fabric#115]
Hi!, sorry I could not find any other tickets related to the build tools version for Android. Feel free to close if this has been discussed somewhere else.
Basically Im trying to upgrade the version of Gradle (and it's plugin) by doing so I get constrained to use android build tools `25.x` and `react-native-fabric` specifies build tools `23.x` therefore android won't compile complaining that the build tools that `react-native-fabric` is using are 'too low'

Actual message: 
<img width="696" alt="screen shot 2017-04-14 at 11 14 45 am" src="https://cloud.githubusercontent.com/assets/1154663/25048740/97a20928-2103-11e7-92bf-55759b1271a2.png">

Any suggestions on how to upgrade the build.gradle configuration of `react-native-fabric` in order to make it play nice with newer versions of gradle.

Thanks!

**Comment by sibelius** [comment]
this is a problem with android, not this lib itself

**Comment by yoelglus** [comment]
I am experiencing the same issue when trying to use this package.
I will submit a PR for this and post a link here.

**Comment by sibelius** [comment]
follow this https://github.com/react-native-community/react-native-camera/pull/1380

**Comment by sibelius** [comment]
fixed on master

**Comment by sibelius** [comment]
https://github.com/corymsmith/react-native-fabric/pull/177
