### ISSUE TITLE
Struggles with iOS and answers.

### ISSUE THREAD

**Issue by vongohren** [corymsmith/react-native-fabric#121]
Im struggeling to get iOS and answers to work with cocapods and swift setup. Im not sure what it might be, I have set fabric like fabric.io tells us, and I have imported this lib with cocapods. But when calling a method on the answers lib i get these error messages:

https://gist.github.com/vongohren/ace1fa40639ebb75b43e465bad51a3bd

Any idea @corymsmith, seen it before?

**Comment by corymsmith** [comment]
@vongohren No I've never seen those errors before. I've also never imported this lib with CocoaPods so I'm not much help unfortunately.

**Comment by vongohren** [comment]
I figured out a solution to this. I ended up making a hardcoded reference,(drag and drop the files into the project), on the node modules folder. It actually works, but is not optimal. Got the idea from airbnb - point 3 - https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#ios

**Comment by vongohren** [comment]
So works for now, when I have time i might look at this, or maybe fabric comes with default react native support.
