### ISSUE TITLE
ios: not archiving unless I remove Pods/React

### ISSUE THREAD

**Issue by fabriziomoscon** [corymsmith/react-native-fabric#126]
Installing React via pods is deprecated.
Following the README instructions you will receive a [React deprecated] Warning.

My project was still building after that but when I tried to archive there were tons of error for React native files not found.

I guess that React dependency should be removed by pods or we should try a workaround similar to this: https://github.com/rebeccahughes/react-native-device-info/issues/63

**Comment by corymsmith** [comment]
I'm open to a PR around this since I don't have the time myself.

**Comment by fabriziomoscon** [comment]
I don't experience this error anymore, so I am not sure what the problem was, neither how to fix it.
