### ISSUE TITLE
Do I add ReactNativeFabric alongside Fabric in Podfile?

### ISSUE THREAD

**Issue by peterpme** [corymsmith/react-native-fabric#131]
Hey!

Awesome library!

I followed the Fabric docs but I'm a bit confused about this part:

```pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'```

Fabric instructed me to put Crashlytics + Fabric into my Podfile, which I did. Now, do I put this alongside of that or do something different?

I'd be happy to update the docs as well to make this clearer!

Thanks,
Peter

**Comment by corymsmith** [comment]
You don't need to install this lib using CocoaPods, if you do then you would need to put both in your pod file

**Comment by peterpme** [comment]
Hey Cory, so just to make sure if I install it using CocoaPods (like Fabric documentation wants you to), I would put both:

```
pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
pod 'Crashlytics'
```

right?

I'd be happy to update the wording on the doc as well!

**Comment by corymsmith** [comment]
@peterpme Yes I believe so, I've personally never installed it that way so I can't be 100% sure. I wasn't the one that added that portion to the docs
