### ISSUE TITLE
Could not install on android RN. 0.46.4

### ISSUE THREAD

**Issue by tiempham** [corymsmith/react-native-fabric#132]
Hey Guy!
I have problem with react-native fabric on android. 
After installed follow [android](https://github.com/corymsmith/react-native-fabric#android) instruction I got error:
* Where:
Build file '/Users/macbook/Documents/JOBS/App/banoitro/android/app/build.gradle' line: 115

* What went wrong:
A problem occurred evaluating project ':app'.
> Cannot change dependencies of configuration ':app:classpath' after it has been resolved.

any idea? Thanks

**Comment by corymsmith** [comment]
I'm guessing you added the dependencies or repositories to the wrong gradle file or the wrong location. Please double check everything again. Closing this for now

**Comment by tiempham** [comment]
You right! I installed follow instruction but i got error so i import classpath to another location ex: app/build_grale -> ./build_gradle.
Thank you.
