### ISSUE TITLE
Please update docs to reflect latest package version

### ISSUE THREAD

**Issue by mdstaff** [corymsmith/react-native-fabric#139]
Hello,

The main page for this github repo & the associated readme file displays the recommended version as: 

Versioning

For React Native > 0.40 use version 0.4.0
For React Native < 0.40 use version 0.3.2
For Twitter Kit support, see react-native-fabric-twitterkit

Should this be updated as the latest tag shows version 0.5.1?

Thanks,
Matt

**Comment by corymsmith** [comment]
Correct. Should show the latest or 0.4.0+ so basically anything above that version

**Comment by corymsmith** [comment]
Fixed
