### ISSUE TITLE
Answers.logLogin() cant add additional config

### ISSUE THREAD

**Issue by rheilgm** [corymsmith/react-native-fabric#141]
are we able to add custom params on logLogin ? 

ex. `Answers.logLogin('Google', true, {userType: 'admin'})`

**Comment by rheilgm** [comment]
tried adding one but i cant see it being reflected on fabric dashboard

**Comment by rheilgm** [comment]
nvm fixed it

**Comment by dauane** [comment]
Hey @rheilgm. How did you fix it?
