### ISSUE TITLE
Can't find place in android side where to put io.fabric.ApiKey

### ISSUE THREAD

**Issue by rkostrab** [corymsmith/react-native-fabric#15]
Hello, I'm developing Android app only and I can't find place where to put `io.fabric.ApiKey`. I've tried to sniff it in your example project - no luck. In android native project it used to be situated in manifest file as a metadata.

e.g. Manifest.xml
```
<Application>
...
<meta-data
            android:name="io.fabric.ApiKey"
            android:value="vf7dhg89shgdf8s9vhsd79fblablablablablabla" />
...
</Application>
```
Logically it can't work without apikey. So where to put apikey?

Thank you

**Comment by alexprice91** [comment]
WOuld this work?
https://docs.fabric.io/android/fabric/integration.html#add-api-key-and-build-secret

**Comment by corymsmith** [comment]
This still an issue? It's typically stored in a .properties file that the Fabric plugin for Android Studio creates. I'll close for now, can reopen if needed
