### ISSUE TITLE
Looking for a maintainer / people to help with react-native-fabric

### ISSUE THREAD

**Issue by corymsmith** [corymsmith/react-native-fabric#154]
I'm not currently using this lib in any projects so I don't have the proper time to maintain it, if anyone has some time and would like to help it would be greatly appreciated.

**Comment by calvinmikael** [comment]
Please put this as a note in large font in the project readme so that future users and potential maintainers can see it easily.

**Comment by josephroque** [comment]
I've just started using the project and would hate to see lose support so soon after. I don't have a lot of time for the next couple months (through the end of January) as I'm still in school and finishing up my last semester, but I'll check back frequently and if nobody is willing/capable/interested, I'd be willing to contribute the time, once February comes around.

**Comment by renatoalencar** [comment]
I'm interested in, since I'm using it in a project and we are upgrading all the project dependencies. I would be happy the help.

**Comment by BigPun86** [comment]
I am interested too...actually i am using this module in all my projects since a quite long time now, and i would have great problems when this loses support :P

**Comment by corymsmith** [comment]
Thanks guys! 

I've just added @renatoalencar amd @BigPun86 as collaborators on the repo, if you're still interested @josephroque I can add you as well.

**Comment by josephroque** [comment]
@corymsmith Hey, this is definitely something I'm still interested in contributing some time too!

**Comment by fjtrujy** [comment]
Hello,
Happy to contribute as well, I'm totally interested on keep this repository updated!

Thanks in advance

**Comment by Salakar** [comment]
Hey all, 

We've added Crashlytics support as part of https://github.com/invertase/react-native-firebase and is being kept up to date over there. We'll be looking into other fabric functionality as and when they move over to Firebase.

**Comment by dann1609** [comment]
I'm very interested in keep this repository update. More if take account one of my long time project need this repository.

**Comment by sibelius** [comment]
Add me as a contributor

**Comment by corymsmith** [comment]
@sibelius done

**Comment by fjtrujy** [comment]
Hello,
I said time ago that I wanted to be a contributor but I think that you forgot my request...

**Comment by watadarkstar** [comment]
@corymsmith Add me as contributor I can help with maintaining this repo

**Comment by avisangray** [comment]
i'm interested in this. since i've been using this for all of my react projects and i'd hate this to be incomptabile for future releases.

**Comment by AndreiCalazans** [comment]
Since you guys gained new contributors would be nice if someone updated the README.

**Comment by sibelius** [comment]
@corymsmith can we add me and more people to release a new version on npm?

my npm user: sibelius

**Comment by corymsmith** [comment]
@sibelius Oh sorry, I had added you to NPM when I added you to a Collaborator on this repo.
