### ISSUE TITLE
Circular dependency while integrating Crashlytics in RN App

### ISSUE THREAD

**Issue by mohanrohith** [corymsmith/react-native-fabric#16]
`What went wrong: Circular dependency between the following tasks: :app:bundleDebugJsAndAssets +--- :app:mergeDebugResources | --- :app:generateDebugResources | --- :app:fabricGenerateResourcesDebug | --- :app:processDebugManifest | --- :app:generateBundledResourcesHashDebug | --- :app:bundleDebugJsAndAssets (*) ' Can someone help to resolve this issue?`

**Comment by corymsmith** [comment]
What's in your build.gradle file?

**Comment by mohanrohith** [comment]
I just followed the usual way of installing from fabric docs

**Comment by corymsmith** [comment]
@mohanrohith Did you get this sorted? I have no idea what could be causing this and I don't think its related to this module, seems like a Fabric issue.

**Comment by mohanrohith** [comment]
Yes sorted out.
 It was an issue with codepush module
