### ISSUE TITLE
IOS Problem with Registering App

### ISSUE THREAD

**Issue by pavanmehta91** [corymsmith/react-native-fabric#160]
Not an issue with the library but I'm using MAC app for fabric and following all the steps but it does not seem to register the App in fabric for crashanalytics.
Here's the message I get 
'Hmmm, seems like your kit isn't activating.'

**Comment by robyweb** [comment]
Did you figure out the issue? Please share your solution.

Thanks,

Fred

**Comment by pavanmehta91** [comment]
Yes I've figured that out. Actually I did not have the admin rights so it did not register the app. When my colleague with the admin rights logged in from his account in the mac app it got registered. Thanks for the support.
