### ISSUE TITLE
Disable Answers & Crashlytics on development [iOS]

### ISSUE THREAD

**Issue by njnest** [corymsmith/react-native-fabric#162]
Hello.
How can I disable Answers and Crashlytics on development in iOS?

**Comment by rudyryk** [comment]
Hello @njnest!

This is probably not `react-native-fabric` question, but rather Fabric / Crashlytics for iOS specific. I would just disabled it with pre-compilder directive in `AppDelegate.m`:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSLog(@"didFinishLaunchingWithOptions: %@", launchOptions);
  
  #if DEBUG
  NSLog(@"didFinishLaunchingWithOptions: skip Fabric init in DEBUG build");
  #else
  [Fabric with:@[[Crashlytics class]]];
  #endif

  // ...
}
```

**Comment by njnest** [comment]
thanks, @rudyryk 

I think this will help.
