### ISSUE TITLE
Two auto-generated fabric files updated on every Android build

### ISSUE THREAD

**Issue by ilyakar** [corymsmith/react-native-fabric#165]
Every time I build my Android project, two fabric files are updated. I tried placing them in gitignore and then removing them, but that caused the app to crash. What can I do with them?

![image](https://user-images.githubusercontent.com/1760709/37960157-2ea41970-31b5-11e8-9367-21c82a5f489e.png)

App crashes when they are removed:
![image](https://user-images.githubusercontent.com/1760709/37960283-913130a0-31b5-11e8-870b-b8ba2eaaabcf.png)

**Comment by corymsmith** [comment]
You can add to .gitignore but you can't remove those files as Fabric / Crashlytics generates them for a reason.
