### ISSUE TITLE
Broken android build on fabric

### ISSUE THREAD

**Issue by lXSPandora** [corymsmith/react-native-fabric#172]
![captura de tela 2018-05-28 as 16 11 20](https://user-images.githubusercontent.com/18129416/40626882-c99a483e-6291-11e8-9729-82f2296db057.png)

**Comment by josephroqueca** [comment]
Identical issue? https://github.com/corymsmith/react-native-fabric/issues/13

Looks as though you might need to follow these steps: https://github.com/corymsmith/react-native-fabric#android-without-android-studio
