### ISSUE TITLE
Framework precedence

### ISSUE THREAD

**Issue by jbrodriguez** [corymsmith/react-native-fabric#174]
Seeing this commit 9d432c2408236049bb87bd319e3fddf69da6be8c, now I wonder ... which version my app actually uses ?

Is it the one bundled with react-native-fabric ? 

Or is it the one we set up in the app's android/build.gradle ?

**Comment by josephroqueca** [comment]
Gradle will resolve to the newest version when there are conflicting definitions. However, the README should have been updated to the same version, and I'll resolve that now.
