### ISSUE TITLE
IOS / XCode error on build: SMXCrashlytics missing RCTBridgeModule.h

### ISSUE THREAD

**Issue by xstable** [corymsmith/react-native-fabric#176]
Cocoapods 1.5.3
XCode 9.3.1

I've installed on android with `react-native install react-native-fabric`.

Then I change to macOS and run `pod install` in /ios.

In my Podfile, I have those lines: 
```
  pod 'Firebase/Core'
  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
```

But if I wan't to run the App in Emulator, I got this error.

![auswahl_865](https://user-images.githubusercontent.com/1778068/42577545-df2452c0-8524-11e8-9943-9587e047ec16.jpg)

**Comment by xstable** [comment]
Solved it by switching to https://rnfirebase.io/

**Comment by mferranti** [comment]
Hello @xstable. I have same issue. How do you switch to rnfirebase.io? with this: https://firebase.google.com/products/crash/?

thanks!!

**Comment by xstable** [comment]
@mferranti yes, I removed fabric and only use rnfirebase.io. It's a pretty completed implementation of Firebase.
