### ISSUE TITLE
undefined is not a function (evaluating SMXCrashlytics.recordError(newError))

### ISSUE THREAD

**Issue by qpowell** [corymsmith/react-native-fabric#21]
Trying to integrate `react-native-fabric` in an Android project I'm working on and this came up. I'm using react-native v0.22.2 and react-native-fabricv0.1.0and followed Fabric's instruction to get Crashlytics running in the app and my project now shows up on the dashboard of my Fabric account.

![screen shot 2016-04-11 at 9 49 30 am](https://cloud.githubusercontent.com/assets/1351050/14431315/b90ae13a-ffca-11e5-8e5c-8eb65b3a0138.png)

Seems to point to Line 52 in Crashlytics.js, which just calls `SMXCrashlytics.recordError(newError);`

I added a `console.log` to take a look at `SMXCrashlytics` in chrome and got this:

![screen shot 2016-04-11 at 9 51 04 am](https://cloud.githubusercontent.com/assets/1351050/14431388/0d19b454-ffcb-11e5-91f0-3078f36e68ae.png)

All the other functions appear to be there. Is there something I'm missing? Any help would be appreciated.

**Comment by lucasmreis** [comment]
Same error here.

**Comment by corymsmith** [comment]
I'll have a look at this today

**Comment by qpowell** [comment]
@corymsmith Thanks. Also, digging that "Developers" song :)

**Comment by corymsmith** [comment]
@qpowell Haha, glad you like it :)

**Comment by corymsmith** [comment]
I had forgotten that @lrettig's PR only added recordError for iOS, I should have added an appropriate error for Android. I'll have to implement recordError on Android and do another release to NPM.

**Comment by qpowell** [comment]
Sounds good. I don't actually need it *yet* but noticed the issue and figured others might be confused since the method is listed in the docs. Look forward to the updated release

**Comment by damusnet** [comment]
Hi, is there any particular reason you didn't push this on npm yet?

**Comment by corymsmith** [comment]
Mainly just been busy, will try to get a release out today

**Comment by doddys** [comment]
same error with version 0.2.1

**Comment by corymsmith** [comment]
So one issue I see with implementing this on Android is that the errors won't show up as being the same error if logged from iOS or Android. The iOS implementation currently creates an NSError like this: 

```
[NSError errorWithDomain:domain code:code userInfo:error]
```

In Android you can't create an exception with an arbitrary dictionary and domain and code are also both only applicable on iOS.

I'm not quite sure what the exact solution should be at this point, any thoughts?

**Comment by npomfret** [comment]
Did this fix ever get released?

**Comment by corymsmith** [comment]
The issue is that recordError doesn't exist in the Android Fabric SDK, and likewise logException only exists on the Android SDK and not iOS. We can proxy one to the other but they take completely different inputs.

**Comment by corymsmith** [comment]
Also, according to @ajwhite in #40, recordError has been removed from the iOS SDK in the latest version. I think the solution is to use answers to log a custom event with custom attributes. Thoughts?

**Comment by npomfret** [comment]
Logging an arbitrary event seems like a suitable solution to me.

**Comment by ajwhite** [comment]
Would that just be a shoe-in the `Crashlytics` methods by rewiring that call to use `Answers`?

My only concern would be unexpected behavior

**Comment by corymsmith** [comment]
@ajwhite since they removed it from their SDK I'm inclined to also remove it from this lib so that the APIs are similar. It's a breaking change so ideally users upgrading would know what was updated (can add a note to the top of the Readme as well)

**Comment by ajwhite** [comment]
I'm not incredibly familiar with objectice-c or swift, but are you able to check if a method is defined on an instance?

If possible, you could keep the function and just show a deprecation notice (I think you can throw "soft exceptions" on native side that would show the red box on the UI side).

If `recordError` does exist, then it can continue to use the method as it currently does. If it doesn't exist, show the deprecation notice

**Comment by corymsmith** [comment]
Quick update on this: `recordError `has not been deprecated from the iOS SDK, we should find a way to have a consistent API to log errors between iOS and Android since the Crashlytics iOS SDK has `recordError` and the Android SDK has `logException`. 

If anyone has time to dig into that I'd love the help :)

**Comment by ajwhite** [comment]
Note that this error appears to be on versions `3.4.x` of Crashlytics. I believe support was introduced in `3.5`, it's certainly in `3.7.x` though.

**Comment by parrunset** [comment]
I've had the same issue. But then I realized that I was doing npm install react-native-fabric and rnpm install react-native-fabric. 

What I did: 
npm install react-native-fabric and rnpm **link** react-native-fabric (note link instead of install) and then rebuild and run the project.

This solved the problem

**Comment by ddagone** [comment]
Same error !

**Comment by parrunset** [comment]
I followed those instructions in order to make it compile and run: https://www.spritle.com/blogs/2016/02/15/integrate-fabricio-crashlytics-to-a-react-native-android-app/
You must add the two apps inside fabric dashboard (android and iOS) (I've benn stucked for a long time trying to log and exception for android in the iOS dashboard). Once done that, for Android you must use Crashlytics.logException('') and for iOS Crashlytics.recordError(''). All is working fine right now

**Comment by npomfret** [comment]
Can we adjust the API so it's the same for android and iOS.  It seems that having `Crashlytics.logException` for Android and `Crashlytics.recordError` is confusing for users.

**Comment by anotherstarburst** [comment]
Yeah - this was pretty confusing. Glad I stumbled upon this thread as the issue had me pretty stressed.

**Comment by Gentlee** [comment]
Had same issue with `SMXCrashlytics.crash` method, reason was that rnpm didn't add `new FabricPackage()` to list in `MainApplication.getPackages()` method. You can check everything here https://github.com/corymsmith/react-native-fabric#without-rnpm.

**Comment by casenjo** [comment]
I just ran into this while trying to get our Android app running. Is the current consensus still to use ```Crashlytics.logException``` for Android and ```Crashlytics.recordError``` for iOS?

**Comment by corymsmith** [comment]
@casenjo Yes, there hasn't been any consolidation done between those 2 calls.

**Comment by casenjo** [comment]
No problem! Thanks for the quick response @corymsmith :)

**Comment by DaniAkash** [comment]
face the same issue mentioned by @Gentlee on android. it worked after linking the libraries manually as specified in https://github.com/corymsmith/react-native-fabric#without-rnpm. After rnpm link `new FabricPackage()` was missing in `MainApplication.getPackages()`
