### ISSUE TITLE
Could not find com.android.tools:common:25.2.3

### ISSUE THREAD

**Issue by phoenix377** [corymsmith/react-native-fabric#210]
### Description

I tried to build my react-native application for android.
AndroidStudio tell me that common:25.2.3 is undefined in jcenter repository.

### How to repeat issue and example

Create a new react application (version should be 0.57.7).
Install and link react-native-fabric.
Open AndroidStudio, ask it to sync project file with gradle files.

### Additional Information

React Native version: 0.57.7
Platform: Android
Development Operating System: MacOS
Dev tools: Android Studio v3.2.1

**Comment by zhuang17** [comment]
i got the same issues.

**Comment by phoenix377** [comment]
This issue is happening because common:25.2.3 is deleted in jcenter.
I added following code in /android/build.gradle and it solves this issue. But it's just hotfix and I think this module needs to be updated.

```
subprojects { project =>
    if (project.name.contains('react-native-fabric')) {
        buildscript {
            repositories {
                google()
                jcenter()
            }

            dependencies {
                classpath 'com.android.tools.build:gradle:3.1.4'
            }
        }
    }
}
```

**Comment by zhuang17** [comment]
yes, the library is missing in [jcenter](https://jcenter.bintray.com/com/android/tools/common/) here.

```

**Comment by krupalagravat** [comment]
Fixed by this 👍  [https://github.com/DylanVann/react-native-fast-image/issues/366#issuecomment-446227637](url)
