### ISSUE TITLE
Digits support

### ISSUE THREAD

**Issue by corymsmith** [corymsmith/react-native-fabric#3]
https://docs.fabric.io/ios/digits/digits.html

**Comment by fungilation** [comment]
There is https://github.com/JeanLebrument/react-native-fabric-digits but that's still lacking Android support. +1 for including Digits properly

**Comment by saidimu** [comment]
FYI https://github.com/JeanLebrument/react-native-fabric-digits now has Android support: https://github.com/JeanLebrument/react-native-fabric-digits#android-procedure

**Comment by sibelius** [comment]
this one works pretty well: https://github.com/fixt/react-native-digits

I think it is not a good idea to have all fabric integration in only one package

**Comment by corymsmith** [comment]
Going to close this since there's lots of other good packages that do this
