### ISSUE TITLE
Please clarify if react-native-fabric is compatible with RN 25+

### ISSUE THREAD

**Issue by rturk** [corymsmith/react-native-fabric#32]
Hi,
I've glanced over the code. Looks like this package is compatible with new import logic introduced in RN25. Although the code looks OK opening this issue anyway so we can track this.

Starting in RN 25 React Native import wil change:

Requiring React API from react-native will be deprecated:
https://github.com/facebook/react-native/releases/tag/v0.25.1

Instead of:

import React, { Component, View } from 'react-native'; 

you should now:

import React, { Component } from 'react';
import { View } from 'react-native';
You can also try this codemod built by the community to automatically rewrite all the imports.
https://github.com/sibeliusseraphini/codemod-RN24-to-RN25

**Comment by sibeliusseraphini** [comment]
it is compatible

**Comment by corymsmith** [comment]
Yes it it, closing this

**Comment by rturk** [comment]
@corymsmith tks!
