### ISSUE TITLE
NullPointerException on twitter login for react-native-image-picker integrated app

### ISSUE THREAD

**Issue by karthickvkumar** [corymsmith/react-native-fabric#33]
Hi @corymsmith Im getting a null pointer exception, if i use [react-native-image-picker](https://github.com/marcshilling/react-native-image-picker) in my [Fabric twitter login] (https://github.com/corymsmith/react-native-fabric) integrated app. 
The twitter login is working fine but, When i try to pick any image form gallery / camera roll it shows an alert of unfortunately app has stopped and get closed.
When i check the stack trace its showing null pointer expection at

> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.twitter.sdk.android.core.identity.TwitterLoginButton.onActivityResult(int, int, android.content.Intent)' on a null object reference

![c5bde1a2-1780-11e6-88eb-4a684ad2a910](https://cloud.githubusercontent.com/assets/11032434/15205293/9969209a-1833-11e6-8ce9-895a3e9158e5.png)

Thanks in Advance

**Comment by ramilushev** [comment]
@karthickvkumar I am seeing this too. I tried removing `mFabricPackage.handleActivityResult(requestCode, resultCode, data);` from `onActivityResult`

It works for the tweet composer but I don't know about login as I am currently not using it.

**Comment by ramilushev** [comment]
@karthickvkumar There was a null check missing. I'll provide a pull request shortly.

**Comment by karthickvkumar** [comment]
Thanks alot @ramilushev
