### ISSUE TITLE
add instructions to include react-native-fabric in package.json

### ISSUE THREAD

**Issue by masterkrang** [corymsmith/react-native-fabric#35]
I followed the iOS instructions here, but then when I committed my code, all the other devs had this error:

> ld: library not found for -lSMXCrashlytics
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

The way I fixed it was to add this to my package json:

> "react-native-fabric": "0.2.1"

Not sure if this is ideal, but seems a lot easier than dragging and dropping things around or writing up docs reminding them to `npm install react-native-fabric`

**Comment by corymsmith** [comment]
This is needed anytime you use npm, it's either that or you use the following which will add it for you.

npm install react-native-fabric --save

The majority of devs have used npm regularly and are familiar with it

**Comment by masterkrang** [comment]
@corymsmith if i add this to my project following the instructions you here, then i push my code, it breaks for other developers when they pull it down. how would they know to run `npm install react-native-fabric --save` (unless i add this to our README or personally message them). what if there were 100 developers on my project, should they all have to manually run this command or wouldn't it make sense to just instruct people to add it to package.json? then anybody could run `npm install` as they do with other libraries without caring which libraries they need to manually install.

**Comment by corymsmith** [comment]
This is a fundamental principle of npm, any dependencies not specified in the package.json won't work for other developers. Feel free to submit a PR to update the Readme.
