### ISSUE TITLE
undefined is not an object (evaluating 'SMXCrashlytics.crash')

### ISSUE THREAD

**Issue by npomfret** [corymsmith/react-native-fabric#39]
My IOS project is crashing. When I add the lines:

```
var Fabric = require('react-native-fabric');
var { Crashlytics } = Fabric;
```

I'm getting this error:

```
[error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'SMXCrashlytics.crash')
[fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'SMXCrashlytics.crash')
```

Any ideas what's wrong?

**Comment by npomfret** [comment]
Ignore this. I screwed up my Xcode project somehow.

**Comment by 8BitRain** [comment]
@npomfret How did you resolve this issue?

**Comment by npomfret** [comment]
This error is almost always a problem with linking.

**Comment by 8BitRain** [comment]
Understood, I ended up getting this to work by manually linking Crashlytics. RNPM link seems to do its job half of the time -_-.

**Comment by mklb** [comment]
tried everything... then a simple `react-native link` solved it for me

**Comment by LeonardPauli** [comment]
The following from the repo readme about manually linking solved if for me, especially the next last step:

> Open your project in Xcode
> Run open node_modules/react-native-fabric/ios
> Drag SMXCrashlytics.xcodeproj into your Libraries group
> Select your main project in the navigator to bring up settings
> Under Build Phases expand the Link Binary With Libraries header
> Scroll down and click the + to add a library
> Find and add libSMXCrashlytics.a under the Workspace group
> ⌘+B
