### ISSUE TITLE
Error throwing on Answers call

### ISSUE THREAD

**Issue by kevando** [corymsmith/react-native-fabric#4]
I'm very excited to get this module working in my project.

However, I load in the Answers code exactly as you have:

var Fabric = require('react-native-fabric');
var { Answers } = Fabric;
Answers.logCustom('Performed a custom event', { bigData: true });

[And I am getting this error](https://i.imgur.com/ouhQwGQ.png)

I have only js experience, so not sure where to begin debugging this. Any help is appreciated. thanks!

**Comment by corymsmith** [comment]
Are you certain that you have the native files added to your project?  Unfortunately I broke my arm just below the shoulder a few days ago so I'm fairly useless at the moment and can't help too much

**Comment by twalling** [comment]
I'm getting the same error, even after having dragged over the `ReactNativeFabric` folder to my libraries group.

**Comment by corymsmith** [comment]
Strange, wondering if its picking up the native module correctly. 

Can you test this and see what it prints out?

```js
var { NativeModules, Platform } = require('react-native');
var SMXAnswers = NativeModules.SMXAnswers;
console.log('----SMXAnswers----);
console.log(SMXAnswers);
console.log('-----------------);
`

**Comment by twalling** [comment]
I'll give it a try and report back.

**Comment by twalling** [comment]
I get undefined, which is what I was expecting. I dragged in the ReactNativeFabric folder as shown here in a screenshot.
![library panel](https://cloud.githubusercontent.com/assets/4907/13165639/38a46784-d68d-11e5-88b3-4ab7e06d69d0.png)

**Comment by sercanov** [comment]
@twalling can you please try with select the contents of ReactNativeFabric folder and drag them into [PROJECT_NAME] folder? They should be in the same directory with AppDelegate. It worked for me.

**Comment by twalling** [comment]
That seemed to do the job, thanks.

**Comment by corymsmith** [comment]
I'm guessing those files weren't properly added to the Compile Sources build phase when they were first included

**Comment by corymsmith** [comment]
@kevando This still an issue? If so can you try making sure that the .m files are in the Compile Sources build phase, and if not add them?
