### ISSUE TITLE
Cannot read property 'crash' of undefined - ios

### ISSUE THREAD

**Issue by farhanmannan** [corymsmith/react-native-fabric#47]
react-native-cli: 0.2.0
react-native: 0.27.2

Have installed Crashlytics according to Fabric.io (which worked), and have followed the instructions for iOS and Android on the README here (I use Android Studio).

In my `App.js` (where I define my top-level view), I have the line `import Fabric from 'react-native-fabric';` - haven't got any further because when I try to run the app in the iOS simulator, I get the red screen of death:
<img width="487" alt="screen shot 2016-06-23 at 12 37 49" src="https://cloud.githubusercontent.com/assets/603598/16301842/96c06614-393f-11e6-8bda-a2937e01f1cb.png">

Any ideas?

**Comment by corymsmith** [comment]
Have you re-run the app / packager after installing everything? Seems like the Native Module isn't loaded

**Comment by farhanmannan** [comment]
reinstalled everything and this time it works. thanks
