### ISSUE TITLE
RN 29 Android installation docs are wrong

### ISSUE THREAD

**Issue by c-h-** [corymsmith/react-native-fabric#53]
I believe that the `onCreate` method override should still be in the MainActivity.java file even for React Native >= 0.29. My app does not build unless that is the case.

**Comment by corymsmith** [comment]
What's the build error?

**Comment by c-h-** [comment]
I could be wrong, not sure what the problem is.

For `./gradlew assembleDebug`
```shell
MainApplication.java:67: error: cannot find symbol
      super.onCreate();
           ^
  symbol: method onCreate()
MainApplication.java:68: error: no suitable method found for with(<anonymous ReactNativeHost>,Crashlytics)
      Fabric.with(this, new Crashlytics());
            ^
    method Fabric.with(Fabric) is not applicable
      (actual and formal argument lists differ in length)
    method Fabric.with(Context,Kit...) is not applicable
      (actual argument <anonymous ReactNativeHost> cannot be converted to Context by method invocation conversion)
MainApplication.java:65: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors
```

This is the code as modified:
```java
import com.smixx.fabric.FabricPackage;
import com.crashlytics.android.Crashlytics;
import io.fabric.sdk.android.Fabric;

@Override
    protected void onCreate() {
      super.onCreate();
      Fabric.with(this, new Crashlytics());
    }
```

And the package is added to the list.

Any ideas?? Thanks!

**Comment by c-h-** [comment]
I did not follow the Readme properly.

I had put the onCreate method inside of 
`private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) { }`
rather than outside of it.

Placing it outside, and making the `protected void onCreate()` -> `public void onCreate()` lets me create a build successfully (mentioned in https://github.com/corymsmith/react-native-fabric/pull/51).
