### ISSUE TITLE
Android start instructions with error in 0.29.1

### ISSUE THREAD

**Issue by greenteamer** [corymsmith/react-native-fabric#54]
Hi!
Thank you for your work, please tell me what i'm doing wrong
I'm getting this error:

`MainApplication.java:29: error: onCreate() in MainApplication cannot override onCreate() in Application
  protected void onCreate() {
                 ^
  attempting to assign weaker access privileges; was public`

this is my MainApplication file: 
`
package com.startmobile;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.react.ReactActivity;
import io.realm.react.RealmReactPackage;
import com.airbnb.android.react.maps.MapsPackage;
import com.BV.LinearGradient.LinearGradientPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.microsoft.codepush.react.CodePush;
import com.smixx.fabric.FabricPackage;
import com.crashlytics.android.Crashlytics;
import io.fabric.sdk.android.Fabric;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  @Override
  protected void onCreate() {
    super.onCreate();
    Fabric.with(this, new Crashlytics());
  }

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

    @Override
    protected String getJSBundleFile() {
      return CodePush.getJSBundleFile();
    }

    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new RealmReactPackage(),
        new CodePush("**********", MainApplication.this, BuildConfig.DEBUG),
        new LinearGradientPackage(),
        new MapsPackage(),
        new FabricPackage(),
        new VectorIconsPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}

`

**Comment by greenteamer** [comment]
I'm has no experience in Java :(
I try to replace 
`@Override
  protected void onCreate() {
  super.onCreate();
  Fabric.with(this, new Crashlytics());
}`
inside `private final ReactNativeHost` 

but i'm getting 
` error: method does not override or implement a method from a supertype
    @Override`

**Comment by jbrodriguez** [comment]
@greenteamer for what it's worth, I had a similar issue. I got it working by

```javascript
public class MainApplication extends Application implements ReactApplication {


	@Override
	public void onCreate() {
	  super.onCreate();
	  Fabric.with(this, new Crashlytics());
	}

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

 ....
```

**Comment by corymsmith** [comment]
The error is fairly descriptive, onCreate needs to be public and its protected in that snippet you posted.

**Comment by corymsmith** [comment]
Assuming that fixes it then a PR to fix the Readme would be ideal

**Comment by greenteamer** [comment]
@jbrodriguez thank a lot!!! it works.
