### ISSUE TITLE
Crashlytics.logException doesn't log to the dashboard as expected

### ISSUE THREAD

**Issue by sjafri5** [corymsmith/react-native-fabric#57]
Hi friends,

So I have finally gotten my app registered and running with fabrics. I have noticed, however, some glitchiness. For example:

When I place a logException on the render method of my first component (in other words, it will definitely run that line of code) the exception isn't registered on the dashboard. Any Ideas why?

Answers sometimes detects when I am using the app and other times, not so much. Since it is just me using it right now, I can tell because total users jump from 0 to 1. Is there any way I can improve its accuracy? Also, the same issue where it doesn't log an Answers method I placed occurs here.

I'm using this for android, RN 18.1 without Android Studio

**Comment by jerson** [comment]
same here :/ 👍

**Comment by mlevkovsky** [comment]
If you are having trouble recording check this article for IOS
http://stackoverflow.com/questions/17818428/crashlytics-is-not-sending-crash-report-from-iphone

Perhaps Android Studio does the same thing when it comes to blocking certain calls.

**Comment by corymsmith** [comment]
Fabric only logs in Release mode

**Comment by rliuzzi** [comment]
Hey @corymsmith  I am not 100% sure that is true, at least for com.crashlytics.sdk.android:crashlytics:2.5.5@aar 

I am seeing logged exceptions in the console, just intermittently in beta mode which is a debuggable application.

**Comment by jdegroot** [comment]
I know I'm really late to this party, but this is still the first Google hit so I thought I'd post something here: according to the new Fabric [documentation](https://docs.fabric.io/android/crashlytics/caught-exceptions.html?caught%20exceptions#) the reports are sent after the app restarts, which worked for me. 

Hope this helps someone.

**Comment by deanpanayotov** [comment]
Thanks @jdegroot. The logs are sent after an app restart. Do you know of any way to forcefully send the logged messages to the server? This functionality seems a bit useless - the app can sit into memory indefinitely or it can get uninstalled after first launch.

**Comment by jdegroot** [comment]
@deanpanayotov I've looked through the Fabric source code a bit and there's a ReportUploader class that sends the reports on startup in the CrashlyticsCore class. Maybe you can do some hacky reflection things to force uploads, but as far as I can tell there's no API for it.
