### ISSUE TITLE
Add Crashlytics.crash

### ISSUE THREAD

**Issue by lrettig** [corymsmith/react-native-fabric#6]
Would be awesome to be able to initiate a crash from the JS side, for testing. See e.g. https://docs.fabric.io/ios/crashlytics/crashlytics.html#cause-a-test-crash. Could PR if it would be helpful. Thanks.

**Comment by lrettig** [comment]
Submitted https://github.com/corymsmith/react-native-fabric/pull/7 for the iOS side

**Comment by lrettig** [comment]
Done on iOS; someone else could add Android

**Comment by AbilashK** [comment]
Submitted https://github.com/corymsmith/react-native-fabric/pull/11 for Android

**Comment by lrettig** [comment]
Awesome! Thanks :)
