### ISSUE TITLE
React Native version 33 changed an interface and it no longer compiles.

### ISSUE THREAD

**Issue by flightlyverduyn** [corymsmith/react-native-fabric#65]
React Native version 33 changed the Interface for ActivityEventListener.  They added  a new parameter for an Activity.

https://github.com/facebook/react-native/releases/tag/v0.33.0 

Release Notes: Add Activity to onActivityResult listener interface (fbd2e13) - @foghina

Details at https://github.com/facebook/react-native/commit/fbd2e139103e3d520f6dfc009d6200f8b8168e35

-  void onActivityResult(int requestCode, int resultCode, Intent data);
+  void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data);

I'm getting an error with TwitterAuthClient.

error: method onActivityResult in class TwitterAuthClient cannot be applied to given types;
            twitterAuthClient.onActivityResult(activity, requestCode, resultCode, data);
                             ^
  required: int,int,Intent
  found: Activity,int,int,Intent
  reason: actual and formal argument lists differ in length
1 error

Thanks

**Comment by corymsmith** [comment]
I don't have the time to fix this at the moment but would accept a PR if someone wants to put one together.

**Comment by flightlyverduyn** [comment]
I looked at this again today - and realized it's not this project.
Argh.  Sorry.
Thanks for your help.
Keep up the good work.
