### ISSUE TITLE
Instantly crashes on Android

### ISSUE THREAD

**Issue by GeoffreyPlitt** [corymsmith/react-native-fabric#66]
I've done all the installation steps, including installing Crashlytics manually as both Android and iOS, setting API key, etc. Then I installed this package to access things via JS.

On iOS this all worked.

On Android, it crashes immediately if the package is included. I'm not even calling any of the API functions. The following code:
```
var Fabric = require('react-native-fabric');
var { Crashlytics } = Fabric;
```

Immediately causes the following RN red error screen:
```
undefined is not an object (evaluating SMXCrahslytics.crash)
```

**Comment by npomfret** [comment]
Usually I find this happens when the linking process hasn't worked.  Check your `MainApplication` for:

```
@Override
    protected List<ReactPackage> getPackages() {
      reactCBLiteManager = new ReactCBLiteManager();

      return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new FabricPackage(), <- this line
      );
    }

  @Override
  public void onCreate() {
    super.onCreate();
    Fabric.with(this, new Crashlytics()); <- this line
  }

```

**Comment by corymsmith** [comment]
@GeoffreyPlitt What version of RN are you on? And did you sort this out?

**Comment by GeoffreyPlitt** [comment]
@corymsmith here's my version info:
```bash
vlt236:stardust-app giro$ react-native --version
react-native-cli: 1.0.0
react-native: 0.32.1
```

Trying it out now. I think part of the problem is that "rnpm link react-native-fabric" makes changes to MainActivity.java instead of MainApplication.java.

**Comment by GeoffreyPlitt** [comment]
@corymsmith  OK, so I got past my previous errors, and now I get more that I need your help with.

```
ExceptionsManager.js:61 Cannot read property 'crash' of undefinedhandleException @ ExceptionsManager.js:61handleError @ InitializeJavaScriptAppEngine.js:115reportFatalError @ error-guard.js:30guardedLoadModule @ require.js:60_require @ require.js:49(anonymous function) @ require-0.js:1executeApplicationScript @ debuggerWorker.js:23message @ debuggerWorker.js:43
ExceptionsManager.js:61 Module AppRegistry is not a registered callable module.
```

**Comment by GeoffreyPlitt** [comment]
@corymsmith Any ideas?

**Comment by GeoffreyPlitt** [comment]
@corymsmith @npomfret @jondot @myusuf3 Working on a deadline, can anyone help?

**Comment by myusuf3** [comment]
Sorry never seen this error.

**Comment by npomfret** [comment]
Have you checked that the linking process has worked? What does your MainApplication look like?

use `react-native link`

**Comment by GeoffreyPlitt** [comment]
Here's our MainApplication.java:
```java
package com.stardust;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import com.facebook.appevents.AppEventsLogger;
import com.brentvatne.react.ReactVideoPackage;
import com.rnfs.RNFSPackage;
import com.imagepicker.ImagePickerPackage;
import com.BV.LinearGradient.LinearGradientPackage;
import com.smixx.fabric.FabricPackage;
import io.fabric.sdk.android.Fabric;
import com.crashlytics.android.Crashlytics;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new FBSDKPackage(mCallbackManager),
          new ReactVideoPackage(),
          new RNFSPackage(),
          new ImagePickerPackage(),
          new LinearGradientPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }

  private static CallbackManager mCallbackManager = CallbackManager.Factory.create();

  protected static CallbackManager getCallbackManager() {
    return mCallbackManager;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    Fabric.with(this, new Crashlytics());
    FacebookSdk.sdkInitialize(getApplicationContext());
    // If you want to use AppEventsLogger to log events.
    AppEventsLogger.activateApp(this);
  }
}
```

Still getting "undefined is not an object / evaluating SMXCrashlytics.crash"

**Comment by npomfret** [comment]
And your js code?  How are you calling the 'crash' function?

**Comment by GeoffreyPlitt** [comment]
I'm not manually calling a crash function, this crash happens on boot.

**Comment by GeoffreyPlitt** [comment]
Any ideas on how to troubleshoot this further?

**Comment by corymsmith** [comment]
@GeoffreyPlitt before you see this exception is there any other one in Logcat?

**Comment by GeoffreyPlitt** [comment]
Update: I've proven this module is the problem.

I created a fresh React-Native 0.33 app with 'react-native init", here:
https://github.com/GeoffreyPlitt/react_native_minimal

Then in a new branch "crashlytics", I installed Crashlytics for Android, and it builds fine, as well as runs fine (no crash on startup)
https://github.com/GeoffreyPlitt/react_native_minimal/tree/crashlytics

Then in a new branch based off that one called "react_native_fabric", I added your module:
https://github.com/GeoffreyPlitt/react_native_minimal/tree/react_native_fabric

Running this last one crashes immediately on startup. The red RN error message says "undefined is not an object (evaluating SMXCrashlytics.crash)"

So, we've got a complete source codebase proving the crash, and where we can get this working. Please clone or fork my repo, test yourselves, and let me know, thanks.

**Comment by GeoffreyPlitt** [comment]
And here are my logs-- no errors or exceptions before this one, from what I can tell.
http://pastebin.com/Cnq8DTEA

**Comment by corymsmith** [comment]
This module isn't being registered at all in your MainApplication which is why that function is showing as undefined.

https://github.com/GeoffreyPlitt/react_native_minimal/blob/react_native_fabric/android/app/src/main/java/com/react_native_minimal/MainApplication.java

getPackages() should also have `new FabricPackage()`

**Comment by GeoffreyPlitt** [comment]
Great! That apparently wasn't done by either "rnpm install" or "react-native link" which is frustrating.

Now I'm able to complete get past this issue of crashing during imports.

But when I do:
```javascript
var Fabric = require('react-native-fabric')
var { Crashlytics } = Fabric;
Crashlytics.crash();
```

I get a red RN error of indexOutOfBounds  ("length=2; index=10") at CrashTest.java:30. Seems like an issue with the core Crashlytics SDK (Java). Is that an error familiar to you guys, or should I troubleshoot with them?

**Comment by GeoffreyPlitt** [comment]
And finally I realize what's going on with this last part. I wish this was more well-documented.

You have to run in release mode (https://facebook.github.io/react-native/docs/signed-apk-android.html, needs a keystore too) to actually send the crash reports to crashlytics.

**Comment by GeoffreyPlitt** [comment]
So: I believe I've gotten past this problem, code is at https://github.com/GeoffreyPlitt/react_native_minimal/tree/react_native_fabric, and I'm working on another issue (https://twittercommunity.com/t/android-crash-report-was-sent-but-does-not-show-in-my-dashboard/74641) that may be related but I'll close this for now.

Thanks for all your help!

**Comment by mahgolfa** [comment]
use
`react-native link react-native-fabric`
