### ISSUE TITLE
Android Examples does not work (undefined is not an object, evaluating NativeModules.AndroidConstants.ServerHost.split)

### ISSUE THREAD

**Issue by GeoffreyPlitt** [corymsmith/react-native-fabric#69]
I'm having a separate problem (#66) and I thought I'd run your example and see if it works for me.

I cloned this repo, went into "example" folder, then "npm install", then "react-native run-android". Before the app loads, I get a red error screen saying "undefined is not an object (evaluating NativeModules.AndroidConstants.ServerHost.split)"

Am I doing something wrong? Do the examples work for anyone on Android?

**Comment by corymsmith** [comment]
This error is due to an older version of React Native: https://github.com/facebook/react-native/issues/9557

**Comment by GeoffreyPlitt** [comment]
I submitted https://github.com/corymsmith/react-native-fabric/pull/70 to upgrade the RN version to 0.33.

However, I still get this error: "undefined is not an object (evaluating 'NativeModules.AndroidConstants.ServerHost.split)"

**Comment by GeoffreyPlitt** [comment]
I believe I've gotten past this problem, code is at https://github.com/GeoffreyPlitt/react_native_minimal/tree/react_native_fabric, and I'm working on another issue (https://twittercommunity.com/t/android-crash-report-was-sent-but-does-not-show-in-my-dashboard/74641) that may be related but I'll close this for now.

Thanks for all your help!
