### ISSUE TITLE
Must initialize singleton error

### ISSUE THREAD

**Issue by walidvb** [corymsmith/react-native-fabric#71]
Hi all,

I'm getting a `Must initialize Fabric before using singleton()` error. I followed the guide, but can't find the mistake i am making(nor anything on google, unfortunately). I assume I am doing something wrong, but can't as of yet figure out what :/
Here is [my code sample](https://gist.github.com/walidvb/dab0f9d52463d534aad21c98c7451652)

Any help greatly appreciated!

**Comment by corymsmith** [comment]
One issue is that your main application needs to override onCreate and initialize Fabric:

@Override
  public void onCreate() {
    super.onCreate();
    Fabric.with(this, new Crashlytics()); <- this line
  }

Have you also installed the Fabric plugin and installed Fabric via instructions on the Fabric website, that's important as well.

**Comment by walidvb** [comment]
Thanks @corymsmith , not sure how i missed that.
I don't think the docs are very clear on that, i'll try and make a PR if you want!
