### ISSUE TITLE
Crashlytics user metadata - does it work? Where do I see it?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [corymsmith/react-native-fabric#74]
Hello,

I'm using this module successfully to send crashes. I'm now trying to set user metadata like this:
```javascript
var { Crashlytics } = require('react-native-fabric')

export function addUserContextToCrashlytics(user) { 
Crashlytics.setUserIdentifier(user.id) 
Crashlytics.setUserName(user.username) 
Crashlytics.setUserEmail(user.email) 
Crashlytics.setString('phone', user.phone) 
Crashlytics.setString('fullName', user.fullName) 
} 
```

The code is being reached and execute fine without error.

But I don't see any of this info in Crashlytics. Where would this show up? Should I be able to see this on a crash?

**Comment by xxsnakerxx** [comment]
@GeoffreyPlitt just press green "View all sessions" button on right side

**Comment by GeoffreyPlitt** [comment]
I don't see any button that says that, anywhere in Crashlytics/Answers. Can you send a screenshot?

**Comment by xxsnakerxx** [comment]
@GeoffreyPlitt ![screenshot](https://dl.dropboxusercontent.com/s/ytqv3fm3jl8vqs8/2016-10-18%20at%2013.39.png)

**Comment by GeoffreyPlitt** [comment]
Thanks, I clicked that and I see sessions, sure. I still don't see any metadata, like userIdentifier, username, and other metadata I've been setting. I don't see that in your screenshot either. Where do I see that?

Here's my version of your screenshot: https://www.dropbox.com/s/xv17l42k04o9kml/Screenshot%202016-10-19%2013.25.10.png?dl=0

**Comment by xxsnakerxx** [comment]
@GeoffreyPlitt 

```js
Crashlytics.setString('js bundle version', APP_VERSION[Platform.OS]);
```

![screenshot](https://dl.dropboxusercontent.com/s/04ghbizvya29gxc/2016-10-20%20at%2008.25.png)

**Comment by GeoffreyPlitt** [comment]
Yup I'm sending the right data and nothing is showing for me in that section.

But I think we can close this, we decided there are too many things not working for Crashlytics+ReactNative so we're moving to BugSnag.

**Comment by justin808** [comment]
@xxsnakerxx: 
I'm seeing the same issue of not seeing the username or email. I do, however, see a custom string or boolean. Maybe the username and email functions are not working.

I just installed everything today with the current version.

@GeoffreyPlitt Any comparison with BugSnag?

**Comment by corymsmith** [comment]
I haven't had a chance to look into this, any idea if the Crashlytics API changed? Or have you reached out to Fabric / Crashlytics about this as it seems like it would be on their side.

**Comment by GeoffreyPlitt** [comment]
@justin808 I found all 3 of Crashlytics services (Crash capturing, Beta for deployments, Answers for metrics) were fairly easy to integrate at first, but all 3 had problems I never got past:
- Beta - never quite worked for everybody, some people repeatedly tried to get the latest version and just downloaded old versions again.
- Crash capturing - UI is very difficult to actually look at the details of a crash. It's like the UI is all pretty shapes and zero UX. Left me wanting to just export crashes in an automated way, which they  do not support (you have to do each one by hand, no webhooks or APIs to setup automated crash integrations, like Slack or Papertrail)
- Answers never worked well-- I sometimes saw the values we inserted, but they were not integrated well with the Crashes products, UI again looked pretty but was impossible to really use  in a powerful, useful way.

I left Crashlytics. I'm loving Bugsnag.
