### ISSUE TITLE
Fabric crashing app on iPhone

### ISSUE THREAD

**Issue by AgtLucas** [corymsmith/react-native-fabric#78]
Hi!

**I don't know if it's a problem of this module or the Crashlytics itself.**

So, I follow the documentation and installed `react-native-fabric` and Fabric as well, everything works fine using iOS simulator, but when I build the app using `Fastlane` to TestFlight, the app crashs on my iPhone as soon as I open it.

Any ideas of how can I track this problem down?

Thanks!

**Comment by corymsmith** [comment]
If you plug in your device can you see any logs in the console? This may be because you didn't run bundle so the compiled bundle isn't included in your app. I doubt it has to do with this module though. Have you tried to run the app in Release mode on your phone or Simulator?

**Comment by AgtLucas** [comment]
@corymsmith Turns out that the problem was with other module. Fixed. :)

Thanks anyway!
