### ISSUE TITLE
Error installing using cocoapods - target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by stewart42** [corymsmith/react-native-fabric#81]
`[!] The 'Pods-****' target has transitive dependencies that include static binaries: (*****/Pods/Crashlytics/iOS/Crashlytics.framework and *****/Pods/Fabric/iOS/Fabric.framework)`

in podfile 
`use_frameworks!`
...
```
    # Fabric
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'TwitterKit'
```
We are using `swift` in portions of our app as it is hybrid app with a mix of native and "react-native" views. 

Any ideas on what I can do to get around this?

**Comment by corymsmith** [comment]
I've never tried this on a Swift app personally so unfortunately I can't help out.

**Comment by corymsmith** [comment]
This last comment MAY help? https://github.com/corymsmith/react-native-fabric/issues/76#issuecomment-259815991

**Comment by stewart42** [comment]
@corymsmith thanks I tried #76, part of the problem is the assumption in the various pathing, that the app is in an `ios` folder. Our app started out as an 'normal' xcode ios app and we have added react-native recently so it isn't based on the `init` project from react-native.

**Comment by ElvisChiang** [comment]
try to uncomment
```
use_frameworks!
```

**Comment by corymsmith** [comment]
Is this still an issue? If so, any ideas on how best to fix it? I'm not currently using CocoaPods or Swift on any projects and I don't have time to test this out or fix it.

**Comment by Snorlock** [comment]
This is an issue still yes, based on: https://github.com/CocoaPods/CocoaPods/issues/2926 and other issued in cocoa pods relating to this.

But a quick workaround, which is not recomended to run in production, ref: https://github.com/CocoaPods/CocoaPods/issues/3289#issuecomment-255448481

`pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    def installer.verify_no_static_framework_transitive_dependencies; end
end`

Other than that, its up to fabric and crashlytics to go from static libraries to dynamic frameworks, ref: https://github.com/CocoaPods/CocoaPods/issues/1993#issuecomment-135163267

**Comment by corymsmith** [comment]
Closing this as it seems to be a CocoaPods issue as mentioned. If anyone has a solution I'm open to a PR
