### ISSUE TITLE
"Must initialize Fabric before using singleton"

### ISSUE THREAD

**Issue by itinance** [corymsmith/react-native-fabric#82]
On RN 0.26 everything works fine. After upgrading to RN 0.34 we encountered on android the exception mentioned in the title. On iOS everything works fine, only android is broken for us.

android/app/build.gradle:
```
dependencies {
    compile project(':react-native-vector-icons')
    compile project(':react-native-uuid-generator')
    compile project(':react-native-sound')
    compile project(':react-native-i18n')
    compile project(':react-native-google-analytics-bridge')
    compile project(':react-native-fs')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-fabric')
    compile project(':react-native-extra-dimensions-android')
    compile project(':react-native-device-info')
    compile project(':react-native-code-push')
    compile project(':react-native-billing')
    compile project(':react-native-sqlite-storage')

    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
         transitive = true;
       }

    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

```

settings.gradle:

```
include ':react-native-fabric'
project(':react-native-fabric').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fabric/android')

```

MainApplication.java:
```

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new VectorIconsPackage(),
            new RNUUIDGeneratorPackage(),
            new RNSoundPackage(),
            new ReactNativeI18n(),
            new GoogleAnalyticsBridgePackage(),
            new RNFSPackage(),
            new RNFetchBlobPackage(),
            new SQLitePluginPackage(),
            new FabricPackage(),
            new ExtraDimensionsPackage(),
            new RNDeviceInfo()
    }
  };

```

Have i something forgotten?

**Comment by corymsmith** [comment]
Are you calling Fabric.with(this, new Crashlytics()); in your onCreate?

**Comment by itinance** [comment]
Thanks for reaching out so quickly! I've added onCreate() now as described in README.

It continues now with:

> * What went wrong:
> A problem occurred evaluating root project 'XXXXXApp'.
> > Failed to apply plugin [id 'io.fabric']
>    > Crashlytics was applied to a project without an Android plugin. Please make sure the Crashlytics plugin is applied after the appropriate Android plugin for your project.
> 

This is the build.gradle where i applied instructions from README.

// Top-level build file where you can add configuration options common to all sub-projects/modules.
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
apply plugin: "com.android.application"

buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'

        // The Fabric Gradle plugin uses an open ended version to react
        // quickly to Android tooling updates
        classpath 'io.fabric.tools:gradle:1.+'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {

  apply plugin: 'io.fabric'

  repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url 'https://maven.fabric.io/public' }
    }

}

```

Have i missed something else?


Oh, and above the "Failed to apply plugin [id 'io.fabric']"  is another error shown:


> 
> Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
> java.lang.IllegalStateException: buildToolsVersion is not specified.
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
> 	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.groovy:444)
> 	at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy:415)
> 	at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy)
> 	at sun.reflect.GeneratedMethodAccessor884.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
> 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
> 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
> 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
> 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
>

**Comment by itinance** [comment]
Missing onCreate() fixes this. Thanks a lot! Incredible fast support! :)

```

public class MainApplication extends Application implements ReactApplication {

  @Override
  public void onCreate() {
      super.onCreate();
      Fabric.with(this, new Crashlytics());
}

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

    @Override
    protected String getJSBundleFile() {
      return CodePush.getJSBundleFile();
    }


```

**Comment by ozanhonamlioglu** [comment]
Hey guys
I just ejected my app with expoKit, but I dont understand there is no any onCreate method.
where should I put  Fabric.with(this, new Crashlytics());

**Comment by bethshook** [comment]
@ozanhonamlioglu Did you ever resolve this? I have the same problem. No onCreate method and when I add one to initialize Fabric, my app immediately crashes.

**Comment by carmelocatalfamo** [comment]
Like @bethshook, I have same issue here.
With `Fabric.with(this, new Crashlytics())` my app crashes.

**Comment by tareqdayya** [comment]
I have done this and it seems to have fixed the problem:

import com.crashlytics.android.Crashlytics;
import io.fabric.sdk.android.Fabric;

public class MainActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      Fabric.with(this, new Crashlytics());
     // setContentView(R.layout.activity_main);
    }
}
