### ISSUE TITLE
iOS builds and runs without error, but does not record data

### ISSUE THREAD

**Issue by dwsc** [corymsmith/react-native-fabric#89]
I set this up for both Android and iOS.  Android is working fine, but my iOS version of the app does not activate with Fabric.  Within my app I'm calling both Crashlytics.crash() and various Answers.logCustom() calls.  None of which trigger any errors.  I've tested in both the simulator (starting, stopping, then re-launching per the documentation), and an installation on a physical device from an archive build.  To debug, I also proxied traffic through Charles to see if any outbound api calls were going to Fabric, and nothing seems to be sent. I'm running version 0.3.2.

**Comment by corymsmith** [comment]
And you're in release mode?

**Comment by corymsmith** [comment]
Sometimes the calls don't get sent until the app is backgrounded or they happen periodically, this is all internal Crashlytics / Fabric stuff and has nothing to do with this lib. If calling methods isn't erroring then this lib is set up correctly. Also some crashes may show up later in the dashboard, a few people have mentioned that. Going to close this as this lib functions correctly.
