### ISSUE TITLE
Handle non-fatal crashes in JavaScript

### ISSUE THREAD

**Issue by lrettig** [corymsmith/react-native-fabric#9]
My application traps a lot of non-fatal errors that occur in JavaScript (actually, this is a byproduct of using A+ compliant promises, which trap errors). I want these to be reported in Crashlytics too.

I tried reporting them as "events" using Google Analytics, and also using Fabric Answers, but the problem is that they both have relatively short limits on the amount of data that can be attached to an event, whereas I need to include a full stack track.

I'm working on a PR to make this happen (as well as converting this code into a fully-fledged Xcode library--this part is done) here: https://github.com/lrettig/react-native-fabric/commits/reporterror-and-xcodeproj

In my tests this is working, I now see these non-fatal JS errors in Crashlytics like this, with the full JS stack track (see below screenshot).

Happy to submit a PR when this is more stable, or whatever you think is best @corymsmith 

![image](https://cloud.githubusercontent.com/assets/3316532/12987898/2f36639e-d0cc-11e5-8b79-4428d66dbb3d.png)

**Comment by corymsmith** [comment]
Whenever you think its good just send over a PR, this is great!

I'm out of commission for another couple weeks with a broken arm but I can merge PR's, etc.

**Comment by lrettig** [comment]
Sorry to hear that, get well soon! I'm building this into a production app that I'm working on, so will definitely clean it up. Might take a few more days though.

**Comment by lrettig** [comment]
My code is done and working! Will submit a PR within the next few days, just fyi

**Comment by lrettig** [comment]
Closing in favor of https://github.com/corymsmith/react-native-fabric/pull/14
