### ISSUE TITLE
React/RCTBridgeModule.h not found

### ISSUE THREAD

**Issue by EdmundMai** [corymsmith/react-native-fabric#93]
```
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h> // <----------------- this line

@interface SMXCrashlytics : NSObject <RCTBridgeModule>

@end
```

**Comment by corymsmith** [comment]
There's a section in the Readme on versioning. You have to use 0.3.2 or upgrade your React-native to 0.40+

**Comment by Suresh-R-S** [comment]
Hi,

In my app's package.json I'am having react native 0.40 and react-native-fabric ^0.4.1 . 
Still I'am experiencing this issue.

I've installed react-native-fabric and linked it manually.

**Comment by eladgel** [comment]
any news on this error?
