### ISSUE TITLE
Installed according to manual install instructions, does not build

### ISSUE THREAD

**Issue by saberking** [corymsmith/react-native-fabric#95]
I am on RN 0.40.0 and can't get this working

I didn't understand what this means:

```You will also need to modify the Run Script Phase that you likely added to Build Phases so that it points to the correct location for the Fabric framework. ```

I know how to add the library to the `Link Binary With Libraries` Build Phase and I also know how to add a new Run Phase. I tried adding a new Run Phase just above the `Link Binary With Libraries` and also tried adding it at the bottom of the `Build Phases` but neither seemed to have any effect, I still get this error

```
Undefined symbols for architecture i386:
  "_CLSNSLog", referenced from:
      -[SMXCrashlytics log:] in libSMXCrashlytics.a(SMXCrashlytics.o)
  "_OBJC_CLASS_$_Answers", referenced from:
      objc-class-ref in libSMXCrashlytics.a(SMXAnswers.o)
  "_OBJC_CLASS_$_CLSStackFrame", referenced from:
      objc-class-ref in libSMXCrashlytics.a(SMXCrashlytics.o)
  "_OBJC_CLASS_$_Crashlytics", referenced from:
      objc-class-ref in libSMXCrashlytics.a(SMXCrashlytics.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

As a last resort I tried react-native install react-native-fabric and rnpm install react-native-fabric but these don't work either. The only method I haven't tried is CocoaPods, but according to #85 this doesn't work either. 

Is RN 0.40.0 supported? If so, what steps are required to install?

Thanks in advance!

**Comment by octohedron** [comment]
Having the same issue on RN 0.40.0

**Comment by octohedron** [comment]
Steps to fix:

Open finder and go to the project directory where you placed `Fabric.framework` and `Crashlytics.framework`, move these two files to your desktop and delete them and the Crashlytics folder you created if you did.

Open your project in xcode and drag the two files to your project's root directory and select create references and copy files if needed.

Add `libz`, `libc++`, `SystemConfiguration.framework` and `Security.framework` to the Link Binary with Libraries.

Linker flags should be `$(inherited)` and `-ObjC`

Run script should be something like 

`"${PROJECT_DIR}/Fabric.framework/run" aosid123u901nd oiasjdoiajhds10293u1noaifusf`

I suggest updating the `README.md`

**Comment by corymsmith** [comment]
@saberking Did you install the Fabric SDK via the Fabric Application or CocoaPods first?

**Comment by saberking** [comment]
@corymsmith Actually I think I might have forgotten that step. Stupid me. Sorry for the false issue. I might get time to look at this again, if I do I will update here

**Comment by corymsmith** [comment]
@saberking So you've got it working?

@octohedron And you got this working as well?

**Comment by saberking** [comment]
@corymsmith not tried again yet, too busy with other stuff. But yes you can assume it would work, if not I can let you know. Thanks :)

**Comment by corymsmith** [comment]
Ok, going to close this for now, we can reopen if needed.

**Comment by octohedron** [comment]
@corymsmith yea I got it working but I would make installing instructions more clear and step by step like my post above.

**Comment by jjhesk** [comment]
it is now not working since I removed the `fabric.framework` from the folder because it happens from [another issue](https://twittercommunity.com/t/crashlytics-causing-build-failures-with-xcode-8-beta-2/70114/15) does this library have stand alone version that we can only link this archive file from the compile time.

**Comment by sircEUNHO** [comment]
@octohedron This fixes the problem. Thanks

**Comment by rjbernaldo** [comment]
thanks @octohedron. +1 on adding to readme.
